import { test, expect } from '@playwright/test';

test('primeiro acesso, usuários, privacidade e pagamento compartilhado', async ({ page }) => {
  await page.goto('/login');
  await page.getByLabel('Usuário', { exact: true }).fill('admin');
  await page.getByLabel('Senha', { exact: true }).fill('TestOnlyPassword2026');
  await page.getByRole('button', { name: 'Entrar no meu espaço' }).click();
  await expect(page.getByRole('heading', { name: 'Crie sua senha pessoal' })).toBeVisible();
  await page.getByLabel('Senha atual ou temporária').fill('TestOnlyPassword2026');
  await page.getByLabel('Nova senha', { exact: true }).fill('654321');
  await page.getByLabel('Confirmar nova senha').fill('654321');
  await page.getByRole('button', { name: 'Salvar minha senha' }).click();
  await expect(page.getByRole('heading', { name: 'Visão geral' })).toBeVisible();

  await page.getByRole('link', { name: 'Usuários', exact: true }).click();
  await page.getByLabel('Nome', { exact: true }).fill('Ana Teste');
  await page.getByLabel('Usuário', { exact: true }).fill('ana');
  await page.getByLabel('Senha temporária').fill('123456');
  await page.getByRole('button', { name: 'Criar usuário', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Usuário criado');

  await page.goto('/?view=new');
  await page.getByLabel('Descrição / origem da conta').fill('Notebook privado');
  await page.getByLabel('Valor (R$)', { exact: true }).fill('3000,00');
  await page.getByLabel('Quantidade total de parcelas').fill('3');
  await page.getByLabel('Observações privadas').fill('Observação secreta do credor');
  const firstDue = await page.getByLabel('Vencimento da primeira acompanhada').inputValue();
  await page.getByRole('button', { name: 'Criar lançamento', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Notebook privado', exact: true })).toBeVisible();
  const privateUrl = page.url();
  await expect(page.locator('.installment')).toHaveCount(3);

  await page.getByRole('link', { name: 'Salário', exact: true }).click();
  await page.getByLabel('Salário mensal (R$)').fill('3000,00');
  await page.getByLabel('A partir do mês').fill(firstDue.slice(0, 7));
  await page.getByRole('button', { name: 'Salvar salário', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Salário salvo');
  await expect(page.locator('tbody tr').first().locator('td').last()).toContainText('2.000,00');
  await page.getByRole('link', { name: 'Simulador de compra', exact: true }).click();
  await page.getByLabel('Nome da simulação').fill('Celular planejado');
  await page.getByLabel('Valor total da compra (R$)').fill('600,00');
  await page.getByLabel('Quantidade de parcelas', { exact: true }).fill('3');
  await page.getByLabel('Primeiro vencimento').fill(firstDue);
  await expect(page.locator('tbody tr').first().locator('td').last()).toContainText('1.800,00');
  await page.getByRole('button', { name: 'Salvar simulação', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Editar simulação' })).toBeVisible();
  const simulationUrl = page.url();
  await page.reload();
  await expect(page.getByLabel('Nome da simulação')).toHaveValue('Celular planejado');
  await page.getByLabel('Valor total da compra (R$)').fill('900,00');
  await page.getByRole('button', { name: 'Salvar alterações' }).click();
  await expect(page.locator('.saved-simulation')).toContainText('900,00');
  await page.reload();
  await expect(page.locator('tbody tr').first().locator('td').last()).toContainText('1.700,00');

  await page.goto('/?view=new');
  await page.getByRole('button', { name: 'Cobrar alguém' }).click();
  await page.getByLabel('Descrição compartilhada').fill('Parte do notebook');
  await page.getByLabel('Valor (R$)', { exact: true }).fill('1500,00');
  await page.getByLabel('Quantidade total de parcelas').fill('3');
  await page.getByLabel('Quem deve pagar?').selectOption({ label: 'Ana Teste' });
  await page.getByLabel('Vincular a uma despesa sua').selectOption({ label: 'Notebook privado' });
  await page.getByRole('button', { name: 'Criar cobrança' }).click();
  await expect(page.getByRole('heading', { name: 'Parte do notebook', exact: true })).toBeVisible();
  const sharedUrl = page.url();
  await page.getByRole('button', { name: 'Sair', exact: true }).click();

  await page.getByLabel('Usuário', { exact: true }).fill('ana');
  await page.getByLabel('Senha', { exact: true }).fill('123456');
  await page.getByRole('button', { name: 'Entrar no meu espaço' }).click();
  await page.getByLabel('Senha atual ou temporária').fill('123456');
  await page.getByLabel('Nova senha', { exact: true }).fill('234567');
  await page.getByLabel('Confirmar nova senha').fill('234567');
  await page.getByRole('button', { name: 'Salvar minha senha' }).click();
  await expect(page.getByRole('heading', { name: 'Visão geral' })).toBeVisible();
  await page.goto(privateUrl);
  await expect(page.getByRole('heading', { name: 'Não encontramos esse lançamento.' })).toBeVisible();
  await page.goto(simulationUrl);
  await expect(page.getByText('Simulação não encontrada.', { exact: true })).toBeVisible();
  await expect(page.getByText('Celular planejado', { exact: true })).toHaveCount(0);
  await page.getByRole('link', { name: 'Salário', exact: true }).click();
  await expect(page.getByLabel('Salário mensal (R$)')).toHaveValue('0,00');
  await page.goto(sharedUrl);
  await expect(page.getByText('Observação secreta do credor')).toHaveCount(0);
  await expect(page.getByText('Notebook privado', { exact: true })).toHaveCount(0);
  await page.locator('summary').filter({ hasText: 'Registrar pagamento' }).first().click();
  await page.getByLabel('Valor pago (R$)').first().fill('200,00');
  await page.getByRole('button', { name: 'Confirmar baixa' }).first().click();
  await expect(page.locator('.detail-stats .featured strong')).toHaveText(/1.300,00/);
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Visão geral' })).toBeVisible();
  await page.screenshot({ path: 'test-results/dashboard-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('heading', { name: 'Visão geral' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/dashboard-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Sair', exact: true }).click();
  await page.getByLabel('Usuário', { exact: true }).fill('admin');
  await page.getByLabel('Senha', { exact: true }).fill('654321');
  await page.getByRole('button', { name: 'Entrar no meu espaço' }).click();
  await expect(page.getByRole('heading', { name: 'Visão geral' })).toBeVisible();
  await page.goto(sharedUrl);
  await expect(page.locator('.detail-stats .featured strong')).toHaveText(/1.300,00/);
  await expect(page.getByText('informado por Ana Teste', { exact: false })).toBeVisible();
  await page.goto(simulationUrl);
  await expect(page.locator('tbody tr').first().locator('td').last()).toContainText('1.700,00');
  await page.getByLabel('Nome da simulação').focus();
  await expect(page.getByRole('heading', { name: 'Editar simulação' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/simulator-mobile.png', fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: 'test-results/simulator-desktop.png', fullPage: true });
  await page.locator('.saved-simulation summary').click();
  await page.getByRole('button', { name: 'Confirmar exclusão' }).click();
  await expect(page.locator('.saved-simulation')).toHaveCount(0);
});
