import { redirect } from "next/navigation";
import { Sprout, ShieldCheck, ArrowRight } from "lucide-react";
import { currentUser } from "@/lib/auth";
import { loginAction } from "@/app/actions";
import { ActionForm, Submit } from "@/components/action-form";
export default async function LoginPage() {
  if (await currentUser()) redirect("/");
  return <main className="login-page"><section className="login-story"><div className="brand"><span className="brand-icon"><Sprout /></span><span>entrecontas<small>FINANÇAS EM FAMÍLIA</small></span></div><div><span className="eyebrow">MENOS CONTAS NA CABEÇA</span><h1>Dinheiro organizado.<br /><em>Relações mais leves.</em></h1><p>Entenda suas despesas, acompanhe cada parcela e acerte as contas com quem faz parte da sua vida.</p><div className="login-illustration"><div><span>Seu próximo passo</span><strong>Mais clareza, todo mês.</strong><div className="fake-bars">{[35, 52, 44, 68, 58, 82, 100].map((n, i) => <i key={i} style={{ height: `${n}%` }} />)}</div></div><span className="float-badge"><ShieldCheck size={19} /> Seu espaço é privado</span></div></div><small>Uma conta para cada pessoa. Tranquilidade para todos.</small></section><section className="login-form"><div><span className="eyebrow">BEM-VINDO AO SEU ESPAÇO</span><h2>Vamos colocar as<br />contas em dia?</h2><p className="muted">Entre com o acesso criado pelo administrador.</p><ActionForm action={loginAction} className="stack"><label>Usuário<input name="username" autoComplete="username" autoCapitalize="none" placeholder="Seu usuário" required maxLength={40} /></label><label>Senha<input name="password" type="password" autoComplete="current-password" placeholder="Sua senha" required maxLength={128} /></label><Submit>Entrar no meu espaço <ArrowRight size={17} /></Submit></ActionForm><p className="helper">Esqueceu a senha? Peça ao administrador para criar uma senha temporária.</p><div className="login-privacy"><ShieldCheck size={19} /><p>Seus dados financeiros só aparecem para você. Cobranças são compartilhadas apenas entre os envolvidos.</p></div></div></section></main>;
}
